---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app uptime-kuma
  namespace: monitoring
spec:
  values:
    global:
      nameOverride: *app

    image:
      repository: louislam/uptime-kuma
      tag: 1.19.6

    service:
      main:
        ports:
          http:
            port: 3001

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/uptime-kuma/${THEME}.css"></head>';
            sub_filter_once on;
          hajimari.io/icon: mdi:alert-circle-check

    volumeClaimTemplates:
      - name: config
        mountPath: /app/data
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"

    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 150Mi
