---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tdarr
  namespace: media
spec:
  values:
    image:
      repository: haveagitgat/tdarr
      tag: 2.00.18

    env:
      TZ: ${TIMEZONE}

    service:
      main:
        ports:
          http:
            port: 8265
          server:
            enabled: true
            protocol: TCP
            port: 8266

    ingress:
      main:
        annotations:
          # cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/icon: mdi:transit-connection-variant

    volumeClaimTemplates:
      - name: config
        mountPath: /app/configs
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"
      - name: data
        mountPath: /app/server
        accessMode: ReadWriteOnce
        size: 15Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"

    persistence:
      tv:
        enabled: true
        existingClaim: nfs-tv
      movies:
        enabled: true
        existingClaim: nfs-movies
      tcache:
        enabled: true
        existingClaim: nfs-tdarr-cache

    podSecurityContext:
      # Required for passthrough of /dev/dri devices from NFD
      # https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html
      supplementalGroups:
        - 44
        - 109
        # Custom Camelus Group(s)
        - 65541
        - 65536
        - 65537

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
        gpu.intel.com/i915: 1
      limits:
        memory: 2000Mi
        gpu.intel.com/i915: 1

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"

    additionalContainers:
      node:
        name: node
        image: haveagitgat/tdarr_node:2.00.18
        imagePullPolicy: IfNotPresent
        env:
          - name: TZ
            value: ${TIMEZONE}
          - name: nodeID
            value: node
          - name: serverIP
            value: localhost
          - name: serverPort
            value: 8266
        volumeMounts:
          - name: config
            mountPath: /app/configs
          - name: data
            mountPath: /app/server
          - name: tv
            mountPath: /tv
          - name: movies
            mountPath: /movies
          - name: tcache
            mountPath: /tcache
