---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
patchesStrategicMerge:
  - ../../../../patch-ss.yaml
  - ../../../../patch-apptemplate.yaml
