---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-minio-pv
  namespace: storage
spec:
  storageClassName: media-minio
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/mnt/user/minio"
  mountOptions:
    - nfsvers=4.2
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - noserverino
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-minio-pvc
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-minio
  resources:
    requests:
      storage: 1Mi
