---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app overseerr
  namespace: media
spec:
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.32.1

    env:
      TZ: ${TIMEZONE}
      PORT: 80
      APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
      LOG_LEVEL: info

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/overseerr/${THEME}.css"></head>';
            sub_filter_once on;
          hajimari.io/icon: mdi:eye

    volumeClaimTemplates:
      - name: config
        mountPath: /app/config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 1500Mi
