---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sabnzbd
  namespace: media
spec:
  values:
    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 3.7.2@sha256:c493413f6f333b3e4dfba1f740fcec8601e4c50f79af864448dc42836ba7f932

    env:
      TZ: ${TIMEZONE}
      SABNZBD__PORT: &port 80
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.media,
        sabnzbd.media.svc,
        sabnzbd.media.svc.cluster,
        sabnzbd.media.svc.cluster.local,
        sabnzbd.${SECRET_DOMAIN}
    envFrom:
      - secretRef:
          name: sabnzbd-secret

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/sabnzbd/${THEME}.css"></head>';
            sub_filter_once on;
          hajimari.io/icon: mdi:download
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"

    persistence:
      downloads:
        enabled: true
        existingClaim: nfs-downloads
      incomplete:
        enabled: true
        type: emptyDir

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 8000Mi
