---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads
  namespace: storage
spec:
  storageClassName: nfs-downloads
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/mnt/user/downloads"
  mountOptions:
    - nfsvers=4.2
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-downloads
  resources:
    requests:
      storage: 1Mi
