---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-download
spec:
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NAS_ADDR}
    path: "/mnt/user/downloads"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-download
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-download
