---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tautulli
  namespace: media
spec:
  values:
    image:
      repository: ghcr.io/onedr0p/tautulli
      tag: 2.12.5@sha256:d0757cd22196df22e251b9be8db9e729493fb573a07d4d957b553c6676e64440
    env:
      TZ: ${TIMEZONE}

    service:
      main:
        ports:
          http:
            port: 8181

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/tautulli/${THEME}.css""></head>';
            sub_filter_once on;
          hajimari.io/icon: mdi:chart-tree

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 500Mi
