---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cyberchef
  namespace: security
spec:
  values:
    image:
      repository: docker.io/mpepping/cyberchef
      tag: v9.55.0

    env:
      TZ: ${TZ}

    service:
      main:
        ports:
          http:
            port: 8000

    ingress:
      main:
        annotations:
          external-dns.home.arpa/enabled: 'false'
          hajimari.io/enable: 'true'
          hajimari.io/icon: hammer-wrench

    resources:
      requests:
        cpu: 15m
        memory: 79M
      limits:
        memory: 79M
