---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-bazarr
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-longhorn
    - name: cluster-apps-sabnzbd
    - name: cluster-apps-radarr
    - name: cluster-apps-sonarr
  path: ./kubernetes/apps/media/bazarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: bazarr
      namespace: media
  interval: 30m
  retryInterval: 1m
  timeout: 3m
