---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kubernetes-schemas
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 3
      strategy: RollingUpdate
    image:
      repository: ghcr.io/onedr0p/kubernetes-schemas-web
      tag: latest@sha256:ecf1c1ddd78885fb92471662bcea52670e7ec684aa8d787f8dd11a17e760b1fc
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          # cert-manager.io/cluster-issuer: letsencrypt-production
          # external-dns.home.arpa/enabled: "true"
          hajimari.io/icon: mdi:code-json
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 100Mi
