---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  interval: 30m
  timeout: 20m
  chart:
    spec:
      chart: alertmanager
      version: 1.7.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"

    config: ""

    extraInitContainers:
      - name: render-config
        image: ghcr.io/onedr0p/alpine:3.18.4@sha256:b0b6f6f42bf9649ccaf0e98cd74d5e123471e2c4a4db4a5ee417b18dde9973a9
        command:
          - "/bin/sh"
          - -c
        args:
          - "[ ! -f /etc/alertmanager/alertmanager.yml ] && envsubst < /data/configfiles/alertmanager.yml > /data/config/alertmanager.yml"
        env:
          - name: SECRET_PUSHOVER_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: alertmanager-secret
                key: pushover_api_token
          - name: SECRET_PUSHOVER_API_USERKEY
            valueFrom:
              secretKeyRef:
                name: alertmanager-secret
                key: pushover_api_userkey
        volumeMounts:
          - name: config
            mountPath: /data/config
          - name: configfiles
            mountPath: /data/configfiles

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        hajimari.io/icon: alarm
      hosts:
        - host: &host "alertmanager.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host

    persistence:
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteOnce
      size: 50Mi

    extraVolumeMounts:
      - name: config
        mountPath: /etc/alertmanager

    extraVolumes:
      - name: config
        emptyDir: {}
      - name: configfiles
        configMap:
          name: alertmanager-configmap
          defaultMode: 420

    resources:
      requests:
        cpu: 11m
        memory: 50M
      limits:
        memory: 99M
