---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: storage
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
      interval: 10m

  values:
    image:
      repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
    nfs:
      server: "${NAS_ADDR}"
      path: "/mnt/user/nfs-storage"
      mountOptions:
        - nfsvers=4.2
        - tcp
        - intr
        - hard
        - noatime
        - nodiratime
    storageClass:
      name: nfs-kube
      defaultClass: false
      pathPattern: "${.PVC.namespace}-${.PVC.name}"
