---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-calibre-pv
  namespace: media
spec:
  storageClassName: media-calibre
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/mnt/user/calibre"
  mountOptions:
    - nfsvers=4.2
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-calibre-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-calibre
  resources:
    requests:
      storage: 1Mi
