---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: media
spec:
  values:
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.359@sha256:c9260f98f6a1284ccc24ccc85b1ca01ed0042cafed1af573426da0c0912cb861

    env:
      TZ: ${TIMEZONE}
      SONARR__INSTANCE_NAME: *app
      SONARR__PORT: &port 80
      SONARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
      SONARR__LOG_LEVEL: info
    envFrom:
      - secretRef:
          name: sonarr-secret

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        annotations:
          # cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/sonarr/${THEME}.css"></head>';
            sub_filter_once on;
          hajimari.io/icon: mdi:television

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 15Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"

    # persistence:
      # scripts:
      #   enabled: true
      #   type: configMap
      #   name: radarr-configmap
      #   subPath: pushover-notify.sh
      #   mountPath: /scripts/pushover-notify.sh
      #   defaultMode: 0775
      #   readOnly: true
    persistence:
      downloads:
        enabled: true
        existingClaim: nfs-downloads
      tv:
        enabled: true
        existingClaim: nfs-tv
      incomplete:
        enabled: true
        type: emptyDir

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
