---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        email_host: "{{ .authentik_email_host }}"
        email_sender: "{{ .authentik_email_sender }}"
        database_name: "{{ .authentik_postgres_db }}"
        postgresql_user: "{{ .authentik_postgres_user }}"
        postgresql_password: "{{ .authentik_postgres_pw }}"
        host: "{{ .authentik_postgres_host }}"
        cookie_secret: "{{ .authentik_cookie_secret }}"
        account_id: "{{ .maxmind_account_id }}"
        license_key: "{{ .maxmind_vector_license_key }}"

  dataFrom:
    - extract:
        key: authentik
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authentik_$1"
    - extract:
        key: MaxMind
      rewrite:
        - regexp:
            source: "(.*)"
            target: "maxmind_$1"
