apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Zaqw23FNy+AwlAo6mj3a1I1QlKCmZiVkS6d5v8eJy5uoTzao3Q==,iv:ex42kujgAjJYu5OjIQw8QOoGsY3hdkZxOCspplWaAJ4=,tag:iVm8+kJW2bi466lzMdZVGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yfwta6arx2pd004tcd54jnkqa4tu8l7f63k07mhfp3qt87fhu5rq9q0fec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSC9uWHduZDkwT2gxaGpU
            cFZMNlY2amJId2dvSTgwUFlVZk8xTDNkS0FnClZVSWp1enhVQ01NYm9JYmVkZVFX
            ZVEvUXR0WS9xUk1TRmVQa04wc0E3TEUKLS0tIDhFSEszdkFBOUoybGhvSEpYOCtk
            bC9WM1A0SGZaWmxjMmhXZ3J1Y3NYU1UKTrcusrGxytHs+ULleNn3HFwD1WfOKw0p
            v1ayYI61V+rJQW3Y/8tXAeLkQPkwYkuCciIx3wzwEewEbPBglxponw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-09T20:02:01Z"
    mac: ENC[AES256_GCM,data:fIt5djd7YaevleR57+CQdUa/+DBhsAIPLKOGfCFa4j+3hdGjmWKuI9rtwxqCQgGmHBIrxxH87Ai7iR87NkbnzJ7uwDNQu1797Q4QKZBRlfkRZmECLPIl5JpNX7GYDJjlgzhO/BfXPtOqTpXMs6lMB0VfNX4NA54uCciot578Hn8=,iv:mGUfGxcdSXcSJeIPapOK6dFX/i+RC4E1Wj+GSwmnZ+Q=,tag:hY4VGwWYqqSFLYMcgk87Qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
