---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app theme-park
  namespace: default
spec:
  values:

    image:
      repository: ghcr.io/onedr0p/theme-park
      tag: 1.13.9@sha256:626343246c032fb712ba4b71d23a57595dcb579cbcfd46ed6b05dc30ecb0a2aa

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: brightness-6

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app

    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 50Mi
