---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app theme-park
  namespace: default
spec:
  values:

    image:
      repository: ghcr.io/onedr0p/theme-park
      tag: 1.13.6@sha256:5f0a11766966429501e62f58e31a0dd422caf6f0100ad078c469f4e8379c89ae

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: brightness-6

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app

    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 50Mi
