---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-loki
  namespace: flux-system
spec:
  suspend: true
  interval: 10m
  path: ./kubernetes/apps/monitoring/loki/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
