---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  values:
    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 4.4.4.7068@sha256:1ac5d9881a0e25b07b6b7e01eaae3d787cac1524e1db7c7010d5a6de38a3112e

    env:
      TZ: ${TIMEZONE}
      RADARR__INSTANCE_NAME: Radarr
      RADARR__PORT: &port 80
      RADARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
      RADARR__LOG_LEVEL: info
    envFrom:
      - secretRef:
          name: radarr-secret

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/radarr/${THEME}.css"></head>';
            sub_filter_once on;
          hajimari.io/icon: mdi:filmstrip

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 15Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"

    # persistence:
      # scripts:
      #   enabled: true
      #   type: configMap
      #   name: radarr-configmap
      #   subPath: pushover-notify.sh
      #   mountPath: /scripts/pushover-notify.sh
      #   defaultMode: 0775
      #   readOnly: true
    persistence:
      downloads:
        enabled: true
        existingClaim: nfs-downloads
      movies:
        enabled: true
        existingClaim: nfs-movies
      incomplete:
        enabled: true
        type: emptyDir

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
