---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-settings
              - kind: Secret
                name: cluster-secrets
      target:
        labelSelector: substitution.flux.home.arpa/enabled=true

    - patch: |-
        interval: 15m
        maxHistory: 3
        install:
          createNamespace: true
        remediation:
          retries: 3
        upgrade:
          cleanupOnFail: true
        remediation:
          retries: 3
        uninstall:
          keepHistory: false
      target:
        labelSelector: substitution.flux.home.ss/enabled=true

    - patch: |-
        chart:
          spec:
            chart: app-template
            version: 1.2.1
            sourceRef:
              kind: HelmRepository
              name: bjw-s
              namespace: flux-system
      target:
        labelSelector: substitution.flux.home.apptemplate/enabled=true
