---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-vector-aggregator
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/monitoring/vector/aggregator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-loki
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-vector-geoipupdate
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/monitoring/vector/geoipupdate
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-vector-agent
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/monitoring/vector/agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    # - name: cluster-apps-vector-geoipupdate
    - name: cluster-apps-vector-aggregator
