---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bazarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bazarr-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # SONARR__API_KEY
        key: sonarr
    - extract:
        # RADARR__API_KEY
        key: radarr
