---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app bazarr
  namespace: media
spec:
  values:
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.3.0@sha256:6f78c727bff1fa56ba1be9fdd3d98e83b71a3405152dd6b47596af754d23e8a0

    env:
      TZ: ${TIMEZONE}
      BAZARR__PORT: &port 6767
    envFrom:
      - secretRef:
          name: bazarr-secret

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/bazarr/${THEME}.css"></head>';
            sub_filter_once on;
          hajimari.io/icon: mdi:subtitles

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"

    persistence:
      downloads:
        enabled: true
        existingClaim: nfs-downloads
      tv:
        enabled: true
        existingClaim: nfs-tv
      movies:
        enabled: true
        existingClaim: nfs-movies
      add-ons:
        enabled: true
        type: emptyDir
        mountPath: /add-ons

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
