---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-thanos
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/monitoring/thanos/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
