apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:wNzKAS1J4oFxhBC9GPVy/17qlC4J/XztNMYmE7nITBZmxivOm2wlMEYFpXliWc5wBOLJnQoZtLOAg2Ow,iv:g/hBnTmu2Ie7WNNiPSickSWHtpHtR7++9orfAtg7wPw=,tag:ciHVbGb6OurqEvBh/eBjzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yfwta6arx2pd004tcd54jnkqa4tu8l7f63k07mhfp3qt87fhu5rq9q0fec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Q1BYdlhobERxK2pDa2hY
            Ti96YVQrMGl3VStlaFV6cnp1bjFnY0FWSVY4CnBHam5CbVNMZzZlTFByejIvcUFq
            bHB5Qy9TRkQyM3puNHRKTUZyT01sU2sKLS0tIHZEdXdNRkFjS3d3M3R0VTRaZmFR
            cUlZc1VaU0xJWllZdU1aYU9rRG5LUEkKTTig5gnk7lkAHgvXHe1p61rgBFDhZini
            kRWxfmU4QlePitBl5NrtXAlZjR9qXPxba4tOZWtwBMxqvssSrwIVfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-09T20:02:02Z"
    mac: ENC[AES256_GCM,data:xzoMmgqy1oDgkrv0U4Ad46qjcw4+gaR9dLX3VwsG3nHarMNRoJEQIpyTmyHa9tYMHIAOjpX75jjWvfHvGfXZ/OBOKuXZbU2sGxTafTZbZoJSgwlrHXPPQONy4+N37yu4SCWBsbqG6JkMl/Fzq/aBijJdi05J0lkyV8TfUfbO1Mk=,iv:drk0j3q6d50JuSCy5pf9glBC5bErfuEJUtWGIbdl4cY=,tag:ZNvFrE84z0Z7vzLhrRU7vA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
