---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-overseerr
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-longhorn
  path: ./kubernetes/apps/media/overseerr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
