---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-grafana
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/monitoring/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
