---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app longhorn
  namespace: storage
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    annotations:
      node.longhorn.io/default-node-tags: '["nvme"]'
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      defaultFsType: ext4
      reclaimPolicy: Delete
    defaultSettings:
      backupstorePollInterval: 300
      defaultDataPath: /mnt/longhorn
      backupTarget: nfs://${NAS_ADDR}:/mnt/user/nfs-backup
      defaultDataLocality: best-effort
      defaultReplicaCount: 3
      defaultLonghornStaticStorageClass: longhorn
      createDefaultDiskLabeledNodes: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      storageMinimalAvailablePercentage: 10
      StorageOverProvisioningPercentage: 110
    ingress:
      enabled: true
      ingressClassName: nginx
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      tlsSecret: "longhorn-tls"
      path: /
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hajimari.io/enable: "true"
        hajimari.io/icon: "cow"
        hajimari.io/appName: "Longhorn"
        # hajimari.io/targetBlank: "true"
        # hajimari.io/info: "Storage"
