---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: thanos-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET_NAME: thanos
        S3_BUCKET_HOST: s3.bjw-s.dev
        S3_BUCKET_REGION: ""
        S3_ACCESS_KEY: "{{ .minio_thanos_access_key }}"
        S3_SECRET_KEY: "{{ .minio_thanos_secret_key }}"
  dataFrom:
    - extract:
        key: Minio
      rewrite:
        - regexp:
            source: "(.*)"
            target: "minio_$1"
