---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-tdarr
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-longhorn
    - name: cluster-apps-sonarr
    - name: cluster-apps-radarr
    - name: cluster-apps-node-feature-discovery
  path: ./kubernetes/apps/media/tdarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
