---
# yaml-language-server: $schema=https://kubernetes-schemas.witl.xyz/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflared-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # token
        key: cloudflared
        property: token
