---
- op: add
  path: /spec/interval
  value: 15m
- op: add
  path: /spec/maxHistory
  value: 3
- op: add
  path: /spec/install
  value:
    createNamespace: true
    remediation:
      retries: 3
- op: add
  path: /spec/upgrade
  value:
    cleanupOnFail: true
    remediation:
      retries: 3
- op: add
  path: /spec/uninstall
  value:
    keepHistory: false
- op: add
  path: /spec/values/controller
  value:
    replicas: 1
    strategy: RollingUpdate
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"
