apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
spec:
  interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 3
      strategy: RollingUpdate
