---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  values:
    image:
      repository: ghcr.io/bjw-s/calibre-web
      tag: 0.6.19@sha256:b73d4d93ba19da08cc24a9326e92d9a771ff5133e354318f985f77acc78c527d

    env:
      CACHE_DIR: /cache
      TZ: ${TIMEZONE}

    service:
      main:
        ports:
          http:
            port: &port 8083

    ingress:
      main:
        annotations:
          auth.home.arpa/enabled: "true"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/calibreweb/${THEME}.css"></head>';
            sub_filter_once on;
          hajimari.io/icon: mdi:book-open-page-variant

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"

    persistence:
      calibre:
        enabled: true
        existingClaim: nfs-calibre
      cache:
        enabled: true
        type: emptyDir
        mountPath: /cache

    resources:
      requests:
        cpu: 15m
        memory: 249M
      limits:
        memory: 299M
