---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/storage/nfs-subdir-external-provisioner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: nfs-subdir-external-provisioner
      namespace: storage
  timeout: 2m
