---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  chart:
    spec:
      chart: goldilocks
      version: 7.3.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  values:
    controller:
      resources:
        requests:
          cpu: 15m
          memory: 145M
        limits:
          memory: 174M
    # vpa:
    #   enabled: true
    #   updater:
    #     enabled: false
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:align-vertical-top
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 64M
