---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  chart:
    spec:
      chart: goldilocks
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  values:
    controller:
      resources:
        requests:
          cpu: 15m
          memory: 145M
        limits:
          memory: 174M
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:align-vertical-top
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 64M
