---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./nfs-pvc/ks.yaml
  - ./longhorn/ks.yaml
  - ./minio/ks.yaml
